"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion";
import { 
  ArrowRight, 
  Cpu, 
  Database, 
  ShieldCheck, 
  CheckCircle2, 
  UserCheck, 
  Sparkles,
  GraduationCap
} from "lucide-react";
import ScrollReveal from "@/components/animations/ScrollReveal";
import TextReveal from "@/components/animations/TextReveal";
import Magnetic from "@/components/animations/Magnetic";
import AnimatedCounter from "@/components/animations/AnimatedCounter";
import RevealMask from "@/components/animations/RevealMask";
import StaggerReveal from "@/components/animations/StaggerReveal";
import LogoTicker from "@/components/animations/LogoTicker";

export default function Home() {
  const testimonials = [
    {
      quote: "RoboNexus has revolutionized our humanoid training pipeline. Their human-in-the-loop datasets cut our validation errors by 40% in under three months.",
      name: "Dr. Elena Rostova",
      role: "Director of Cognitive Robotics, SynthKinematics",
    },
    {
      quote: "The reliability of data generated by RoboNexus contractors is unmatched. They don't just label data; they execute complex real-world trials that ground our AI.",
      name: "Marcus Vance",
      role: "Lead Machine Learning Architect, AutoDrive Systems",
    },
    {
      quote: "Finding high-quality human demonstration data for custom manipulation tasks was a bottleneck until we partnered with RoboNexus. Founded in 2025, they are the future.",
      name: "Sarah Jenkins",
      role: "VP of Product, NeuralScale AI",
    }
  ];

  return (
    <div className="relative w-full">
      {/* Hero Section */}
      <section className="relative min-h-[85vh] flex items-center justify-center pt-6 pb-12 overflow-hidden">
        {/* Soft hero glows */}
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[450px] h-[450px] rounded-full bg-brand-purple/10 blur-[130px] pointer-events-none" />
        <div className="absolute top-1/3 left-1/3 -translate-y-1/2 w-[300px] h-[300px] rounded-full bg-brand-violet/10 blur-[100px] pointer-events-none" />
        
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 lg:grid-cols-2 gap-10 items-center relative z-10 w-full">
          <motion.div
            initial={{ opacity: 0, y: 25 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: "easeOut" }}
            className="flex flex-col gap-5 text-left"
          >
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-brand-card border border-brand-purple/30 text-xs font-semibold text-brand-violet w-fit backdrop-blur-sm">
              <Sparkles className="h-3.5 w-3.5 text-brand-purple animate-pulse" />
              Empowering Next-Gen Autonomy
            </div>
            
            <div className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight text-white leading-tight">
              <TextReveal text="Real Humans." />
              <TextReveal text="Real Actions." className="text-gradient" delay={0.5} />
              <TextReveal text="Real Impact on AI." delay={1} />
            </div>
            
            <p className="text-base sm:text-lg text-gray-300 max-w-xl leading-relaxed">
              RoboNexus bridges human expertise and neural networks. We curate, record, and validate high-fidelity human dataset manipulation and interactive cognitive sequences that enable robots to understand and master the physical world.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 mt-1">
              <Link href="/register">
                <Magnetic>
                  <motion.button
                    whileHover={{ scale: 1.03 }}
                    whileTap={{ scale: 0.98 }}
                    className="w-full sm:w-auto relative inline-flex items-center justify-center gap-2 overflow-hidden rounded-xl bg-gradient-to-r from-brand-purple to-brand-indigo px-8 py-3.5 font-bold text-white shadow-lg shadow-brand-purple/20 hover:shadow-brand-purple/40 transition-all cursor-pointer"
                  >
                    Join as Contractor
                    <ArrowRight className="h-5 w-5" />
                  </motion.button>
                </Magnetic>
              </Link>
              
              <Link href="/services">
                <Magnetic>
                  <motion.button
                    whileHover={{ scale: 1.03 }}
                    whileTap={{ scale: 0.98 }}
                    className="w-full sm:w-auto flex items-center justify-center gap-2 rounded-xl border border-brand-card-border bg-brand-card hover:bg-brand-card/85 px-8 py-3.5 font-bold text-white transition-all cursor-pointer"
                  >
                    Explore Services
                  </motion.button>
                </Magnetic>
              </Link>
            </div>
          </motion.div>
          
          {/* Hero Media Container */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] as [number, number, number, number] }}
            className="relative w-full h-[320px] sm:h-[420px] rounded-3xl overflow-hidden border border-brand-card-border shadow-2xl bg-brand-dark/40 backdrop-blur-sm group"
          >
            <RevealMask className="h-full w-full" delay={0.4}>
              <div className="absolute inset-0 bg-gradient-to-t from-brand-dark via-transparent to-transparent z-10 opacity-60" />
              <Image
                src="/hero_humans.png"
                alt="Real Humans impacting AI - RoboNexus"
                fill
                priority
                className="object-cover transition-transform duration-1000 group-hover:scale-105"
              />
            </RevealMask>
            {/* Corner glowing element */}
            <div className="absolute bottom-5 left-5 z-20 flex items-center gap-2.5 bg-[#0b0b0f]/85 backdrop-blur-md px-3.5 py-2 rounded-2xl border border-brand-purple/20">
              <span className="flex h-2 w-2 relative">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-brand-purple opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2 w-2 bg-brand-purple"></span>
              </span>
              <span className="text-xs font-mono text-gray-300">RoboNexus System v4.5 Active</span>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Trust Stats Section */}
      <section className="py-12 border-y border-brand-card-border/30 bg-brand-dark/50 backdrop-blur-md relative z-20">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
            {[
              { label: "Active Models Trained", value: 150, suffix: "+" },
              { label: "Data Points Verified", value: 12, suffix: "M+" },
              { label: "Global Contractors", value: 4500, suffix: "+" },
              { label: "Accuracy Rating", value: 99, suffix: ".9%" },
            ].map((stat, idx) => (
              <div key={idx} className="flex flex-col items-center text-center">
                <AnimatedCounter 
                  value={stat.value} 
                  suffix={stat.suffix} 
                  className="text-3xl md:text-4xl font-bold text-white mb-1" 
                />
                <span className="text-xs font-mono text-brand-violet uppercase tracking-wider">{stat.label}</span>
              </div>
            ))}
          </div>
        </div>
        <LogoTicker />
      </section>

      {/* Who We Are Section */}
      <section className="py-16 relative bg-[#15171c]/20 backdrop-blur-sm">
        <div className="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-brand-card-border/60 to-transparent" />
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-center">
            <div className="lg:col-span-5 flex flex-col gap-4">
              <ScrollReveal direction="left">
                <span className="text-xs font-bold font-mono tracking-widest text-brand-violet uppercase">
                  Founded in 2025
                </span>
                <TextReveal 
                  text="Pioneering the Synergy of Human Instinct & Neural Logic" 
                  className="text-3xl sm:text-4xl font-bold tracking-tight text-white mt-1"
                />
                <p className="text-gray-300 mt-4 leading-relaxed text-sm sm:text-base">
                  Established with a forward-looking vision, RoboNexus addresses the most critical bottleneck in modern artificial intelligence: high-quality, real-world interactive data.
                </p>
                <p className="text-gray-300 mt-2 leading-relaxed text-sm sm:text-base">
                  We believe machine learning algorithms shouldn&apos;t just learn from static websites or synthetically generated graphics. They require tactile feedback, human demonstration, and cognitive problem-solving datasets captured in real-world settings.
                </p>
              </ScrollReveal>
            </div>
            
            <div className="lg:col-span-7">
              <StaggerReveal className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                {[
                  {
                    icon: <UserCheck className="h-5 w-5 text-brand-purple" />,
                    title: "Real Humans, Real Impact",
                    desc: "Our globally distributed contractors conduct hands-on training, testing, and alignment protocols directly impacting active model generations."
                  },
                  {
                    icon: <Cpu className="h-5 w-5 text-brand-violet" />,
                    title: "Future Tech Alignment",
                    desc: "We build infrastructure specifically formatted for robotic manipulation, spatial computing, and complex industrial systems."
                  },
                  {
                    icon: <Database className="h-5 w-5 text-brand-purple" />,
                    title: "Rich Datasets",
                    desc: "From physical kinematic recordings to complex logical reasoning steps, we package and stream clean datasets directly to AI labs."
                  },
                  {
                    icon: <ShieldCheck className="h-5 w-5 text-brand-violet" />,
                    title: "Enterprise Rigor",
                    desc: "Every interaction is logged, validated, and scrubbed for PII, maintaining absolute compliance and top-tier training security."
                  }
                ].map((item, idx) => (
                  <div key={idx} className="glow-card p-5 rounded-2xl flex flex-col gap-2.5 h-full">
                    <div className="p-2.5 bg-brand-dark w-fit rounded-xl border border-brand-card-border">
                      {item.icon}
                    </div>
                    <h3 className="text-base font-bold text-white mt-1">{item.title}</h3>
                    <p className="text-xs sm:text-sm text-gray-400 leading-relaxed">{item.desc}</p>
                  </div>
                ))}
              </StaggerReveal>
            </div>
          </div>
        </div>
      </section>

      {/* What We Do Section */}
      <section className="py-16 relative overflow-hidden">
        <div className="absolute top-1/2 left-1/4 -translate-y-1/2 w-[350px] h-[350px] rounded-full bg-brand-purple/5 blur-[100px] pointer-events-none" />
        
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <ScrollReveal>
              <span className="text-xs font-bold font-mono tracking-widest text-brand-violet uppercase">
                Core Operations
              </span>
              <TextReveal 
                text="Powering AI Scaling Pipelines" 
                className="text-3xl sm:text-4xl font-bold tracking-tight text-white mt-1 justify-center"
              />
              <p className="text-gray-400 mt-3 text-sm sm:text-base">
                We operate end-to-end telemetry pipelines that deliver training data for AI models scaling to general intelligence.
              </p>
            </ScrollReveal>
          </div>

          <StaggerReveal className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              {
                title: "Physical Robotics Telemetry",
                desc: "We record real human movements, micro-gestures, and tool handling sequences via spatial sensors to build fine-tuned robotic manipulation datasets.",
                image: "/robotics_arm.png",
                tag: "Robotics Data"
              },
              {
                title: "Human-in-the-loop (RLHF)",
                desc: "We conduct Reinforcement Learning from Human Feedback under strict frameworks, testing edge cases and mitigating alignment drift in real-time.",
                image: "/training_ai.png",
                tag: "RLHF & Align"
              },
              {
                title: "Edge Case Action Verification",
                desc: "Our contractors simulate complex physical failures to test and catalog machine recovery routes, ensuring real-world AI durability.",
                image: "/hero_humans.png",
                tag: "Verification"
              }
            ].map((service, idx) => (
              <div key={idx} className="glow-card rounded-2xl overflow-hidden h-full flex flex-col group">
                <div className="relative h-44 w-full">
                  <RevealMask className="h-full w-full">
                    <Image
                      src={service.image}
                      alt={service.title}
                      fill
                      className="object-cover transition-transform duration-1000 group-hover:scale-110"
                    />
                  </RevealMask>
                  <div className="absolute inset-0 bg-gradient-to-t from-brand-card to-transparent" />
                  <span className="absolute top-3 right-3 bg-brand-dark/85 backdrop-blur-sm border border-brand-purple/20 px-2.5 py-0.5 rounded-full text-2xs font-mono text-brand-violet">
                    {service.tag}
                  </span>
                </div>
                <div className="p-5 flex flex-col gap-2.5 flex-grow">
                  <h3 className="text-lg font-bold text-white">{service.title}</h3>
                  <p className="text-xs sm:text-sm text-gray-400 leading-relaxed flex-grow">{service.desc}</p>
                  <Link 
                    href="/services" 
                    className="inline-flex items-center gap-1.5 text-xs font-semibold text-brand-violet hover:text-white transition-colors mt-3 w-fit"
                  >
                    Read specifications
                    <ArrowRight className="h-3 w-3" />
                  </Link>
                </div>
              </div>
            ))}
          </StaggerReveal>
        </div>
      </section>

      {/* Manufacturing & Education Section */}
      <section className="py-16 relative overflow-hidden">
        <div className="absolute top-1/2 right-1/4 -translate-y-1/2 w-[350px] h-[350px] rounded-full bg-brand-cyan/5 blur-[100px] pointer-events-none" />
        
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="flex flex-col gap-6">
              <ScrollReveal>
                <span className="text-xs font-bold font-mono tracking-widest text-brand-cyan uppercase">
                  Beyond Data
                </span>
                <TextReveal 
                  text="We Build the Robots that Shape the Future" 
                  className="text-3xl sm:text-4xl font-bold tracking-tight text-white mt-1"
                />
                <p className="text-gray-300 mt-4 leading-relaxed text-sm sm:text-base">
                  RoboNexus is not just a data provider; we are a premier **robotic manufacturing company**. From custom humanoid actuators to industrial autonomous platforms, we design and build the hardware that powers next-generation automation.
                </p>
                <p className="text-gray-300 mt-2 leading-relaxed text-sm sm:text-base">
                  Our state-of-the-art facilities produce high-precision robotic arms, sensor arrays, and integrated AI cores used by laboratories and industries worldwide.
                </p>
              </ScrollReveal>

              <div className="bg-brand-card/50 border border-brand-card-border p-6 rounded-2xl">
                <div className="flex items-center gap-3 mb-3">
                  <GraduationCap className="h-6 w-6 text-brand-cyan" />
                  <h3 className="text-lg font-bold text-white">Academic AI Training</h3>
                </div>
                <p className="text-sm text-gray-400 leading-relaxed">
                  We are committed to nurturing the next generation of engineers. Our specialized **AI Training for Students** program provides hands-on experience with real-world robotics hardware and advanced neural network architectures.
                </p>
                <Link href="/training" className="inline-flex items-center gap-2 text-brand-cyan hover:text-white transition-colors mt-4 text-sm font-semibold">
                  Learn about student programs
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </div>
            </div>

            <ScrollReveal direction="right">
              <div className="relative h-[400px] sm:h-[500px] rounded-3xl overflow-hidden border border-brand-card-border group">
                <RevealMask className="h-full w-full">
                  <Image
                    src="/product_core.png"
                    alt="RoboNexus Manufacturing Facility"
                    fill
                    className="object-cover transition-transform duration-1000 group-hover:scale-105"
                  />
                </RevealMask>
                <div className="absolute inset-0 bg-gradient-to-t from-brand-dark/80 via-transparent to-transparent" />
                <div className="absolute bottom-6 left-6">
                  <span className="bg-brand-cyan/20 backdrop-blur-md border border-brand-cyan/30 px-3 py-1 rounded-full text-xs font-mono text-brand-cyan">
                    Manufacturing Hub v2.0
                  </span>
                </div>
              </div>
            </ScrollReveal>
          </div>
        </div>
      </section>

      {/* Why RoboNexus Section */}
      <section className="py-16 relative bg-[#15171c]/20 backdrop-blur-sm">
        <div className="absolute top-0 left-0 right-0 h-[1px] bg-gradient-to-r from-transparent via-brand-card-border/60 to-transparent" />
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center">
            <div className="relative h-[280px] sm:h-[380px] rounded-3xl overflow-hidden border border-brand-card-border order-last lg:order-first">
              <Image
                src="/robotics_arm.png"
                alt="AI Robotic arm training data capture"
                fill
                className="object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-r from-brand-dark/40 to-transparent" />
            </div>

            <div className="flex flex-col gap-5">
              <ScrollReveal>
                <span className="text-xs font-bold font-mono tracking-widest text-brand-violet uppercase">
                  Why RoboNexus
                </span>
                <TextReveal 
                  text="Enterprise-Grade Infrastructure for High-Volume Data" 
                  className="text-3xl sm:text-4xl font-bold tracking-tight text-white mt-1"
                />
                <p className="text-gray-300 mt-3 leading-relaxed text-sm sm:text-base">
                  We don&apos;t just deliver crowdsourced labeling. We run a secure, trained network of professional telemetry specialists globally who operate under strict KPIs to ensure data completeness and high-fidelity output.
                </p>
              </ScrollReveal>

              <div className="flex flex-col gap-3 mt-1">
                {[
                  "Active data validation via triple-blind QA checks",
                  "99.9% semantic alignment across high-dimensional datasets",
                  "Secure sandbox environments for proprietary robot software testing",
                  "Zero data leakage Guarantee under strict compliance mandates"
                ].map((text, idx) => (
                  <ScrollReveal key={idx} delay={idx * 0.08}>
                    <div className="flex items-start gap-2.5">
                      <CheckCircle2 className="h-4.5 w-4.5 text-brand-purple shrink-0 mt-0.5" />
                      <span className="text-xs sm:text-sm text-gray-200">{text}</span>
                    </div>
                  </ScrollReveal>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-16 relative overflow-hidden">
        <div className="absolute bottom-10 right-10 w-[350px] h-[350px] rounded-full bg-brand-purple/5 blur-[100px] pointer-events-none" />
        
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center max-w-2xl mx-auto mb-12">
            <ScrollReveal>
              <span className="text-xs font-bold font-mono tracking-widest text-brand-violet uppercase">
                Endorsements
              </span>
              <TextReveal 
                text="Trusted by Leading AI Foundations" 
                className="text-3xl sm:text-4xl font-bold tracking-tight text-white mt-1 justify-center"
              />
              <p className="text-gray-400 mt-3 text-sm sm:text-base">
                See how top robotics and neural network laboratories leverage RoboNexus data to break intelligence barriers.
              </p>
            </ScrollReveal>
          </div>

          <StaggerReveal className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map((t, idx) => (
              <div key={idx} className="glow-card p-6 rounded-2xl h-full flex flex-col justify-between group">
                <div className="flex flex-col gap-3">
                  <span className="text-4xl text-brand-purple/20 font-serif leading-none select-none">&ldquo;</span>
                  <p className="text-sm text-gray-300 leading-relaxed italic -mt-2">
                    {t.quote}
                  </p>
                </div>
                <div className="mt-6 border-t border-brand-card-border/60 pt-3 flex flex-col">
                  <span className="font-bold text-white text-sm">{t.name}</span>
                  <span className="text-xs text-brand-violet mt-0.5">{t.role}</span>
                </div>
              </div>
            ))}
          </StaggerReveal>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-12 relative overflow-hidden">
        <div className="max-w-5xl mx-auto px-6">
          <ScrollReveal>
            <div className="relative rounded-3xl overflow-hidden border border-brand-card-border bg-gradient-to-br from-brand-card to-[#0b0b0f] px-6 py-12 sm:px-12 text-center shadow-2xl">
              {/* background decorative light */}
              <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(45,126,255,0.05)_0%,transparent_70%)] pointer-events-none" />
              
              <div className="relative z-10 flex flex-col items-center gap-5 max-w-2xl mx-auto">
                <Cpu className="h-10 w-10 text-brand-purple animate-pulse" />
                <TextReveal 
                  text="Ready to Train the Future?" 
                  className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight justify-center"
                />
                <p className="text-gray-300 text-xs sm:text-sm leading-relaxed">
                  Join our verified contractor network or partner with us to stream rich, high-fidelity datasets straight to your training pipeline.
                </p>
                <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto mt-2">
                  <Link href="/register">
                    <Magnetic>
                      <motion.button
                        whileHover={{ scale: 1.03 }}
                        whileTap={{ scale: 0.95 }}
                        className="w-full sm:w-auto relative inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-brand-purple to-brand-indigo px-8 py-3 font-bold text-white shadow-lg cursor-pointer"
                      >
                        Onboard as Contractor
                        <ArrowRight className="h-4 w-4" />
                      </motion.button>
                    </Magnetic>
                  </Link>
                  <Link href="/contact">
                    <Magnetic>
                      <motion.button
                        whileHover={{ scale: 1.03 }}
                        whileTap={{ scale: 0.95 }}
                        className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-xl border border-brand-card-border bg-brand-dark/50 hover:bg-brand-dark px-8 py-3 font-bold text-white transition-all cursor-pointer"
                      >
                        Talk to an Expert
                      </motion.button>
                    </Magnetic>
                  </Link>
                </div>
              </div>
            </div>
          </ScrollReveal>
        </div>
      </section>
    </div>
  );
}


